name: Multistage Java CICD

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build stage
    runs-on: ubuntu-latest

    steps:
      - name: git checkout code
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with maven
        run: mvn clean compile
  test:
    name: Test statge
    runs-on: ubuntu-latest

    steps:
      - name: git checkout code
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with maven
        run: mvn test

  deploy:
    name: Deploy stage
    runs-on: ubuntu-latest

    steps:
      - name: mock deploy
        run : echo "deploying application"




